// <auto-generated />
#nullable enable
using System;
using System.Resources;
using System.Globalization;

namespace TeamsAudioCapture.Properties;

public static class Resources
{
    private static readonly ResourceManager ResourceManager = new("TeamsAudioCapture.Properties.Resources", typeof(Resources).Assembly);

    public static string SettingsSubtitleLiveApi => ResourceManager.GetString(nameof(SettingsSubtitleLiveApi), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsLiveProviderTitle => ResourceManager.GetString(nameof(SettingsLiveProviderTitle), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsLiveProviderLabel => ResourceManager.GetString(nameof(SettingsLiveProviderLabel), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsLiveProviderGemini => ResourceManager.GetString(nameof(SettingsLiveProviderGemini), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsLiveProviderOpenAi => ResourceManager.GetString(nameof(SettingsLiveProviderOpenAi), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiTitle => ResourceManager.GetString(nameof(SettingsOpenAiTitle), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiApiKeyLabel => ResourceManager.GetString(nameof(SettingsOpenAiApiKeyLabel), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiApiKeyHelp => ResourceManager.GetString(nameof(SettingsOpenAiApiKeyHelp), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiModelLabel => ResourceManager.GetString(nameof(SettingsOpenAiModelLabel), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiModelHelp => ResourceManager.GetString(nameof(SettingsOpenAiModelHelp), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsProcessWithLiveApi => ResourceManager.GetString(nameof(SettingsProcessWithLiveApi), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string MainSubtitleLiveApi => ResourceManager.GetString(nameof(MainSubtitleLiveApi), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string MainLiveResponses => ResourceManager.GetString(nameof(MainLiveResponses), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsOpenAiLinkText => ResourceManager.GetString(nameof(SettingsOpenAiLinkText), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string ValidationOpenAiApiKeyRequired => ResourceManager.GetString(nameof(ValidationOpenAiApiKeyRequired), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string ValidationGeminiApiKeyRequired => ResourceManager.GetString(nameof(ValidationGeminiApiKeyRequired), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string SettingsProviderDescription => ResourceManager.GetString(nameof(SettingsProviderDescription), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string OpenAiFileUploadNotSupported => ResourceManager.GetString(nameof(OpenAiFileUploadNotSupported), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string MainResponsesPlaceholder => ResourceManager.GetString(nameof(MainResponsesPlaceholder), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string TranscriptEnabledMessage => ResourceManager.GetString(nameof(TranscriptEnabledMessage), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string TranscriptHiddenMessage => ResourceManager.GetString(nameof(TranscriptHiddenMessage), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string RecordingStartedMessage => ResourceManager.GetString(nameof(RecordingStartedMessage), CultureInfo.CurrentUICulture) ?? string.Empty;
    public static string ValidationRecordingMode => ResourceManager.GetString(nameof(ValidationRecordingMode), CultureInfo.CurrentUICulture) ?? string.Empty;
}
